export const DESTINOS = [
  {
    idDestino: 1,
    destino: "RM",
    ubicacion: "Riviera Maya",
    status: "A",
    bandera: "cun.svg",
    division: 901,
    superficie: "850000",
    habitaciones: 1554,
  },
  {
    idDestino: 2,
    destino: "PVR",
    ubicacion: "Puerto Vallarta",
    status: "A",
    bandera: "pvr.svg",
    division: 900,
    superficie: "84000",
    habitaciones: 518,
  },
  {
    idDestino: 3,
    destino: "SDQ",
    ubicacion: "Santo Domingo",
    status: "A",
    bandera: "sdq.svg",
    division: 911,
    superficie: "43000",
    habitaciones: 269,
  },
  {
    idDestino: 4,
    destino: "SSA",
    ubicacion: "Imbassaí",
    status: "A",
    bandera: "ssa.svg",
    division: 930,
    superficie: "170000",
    habitaciones: 654,
  },
  {
    idDestino: 5,
    destino: "PUJ",
    ubicacion: "Bávaro",
    status: "A",
    bandera: "puj.svg",
    division: 910,
    superficie: "780000",
    habitaciones: 1993,
  },
  {
    idDestino: 6,
    destino: "MBJ",
    ubicacion: "Jamaica",
    status: "A",
    bandera: "mbj.svg",
    division: 920,
    superficie: "340000",
    habitaciones: 1054,
  },
  {
    idDestino: 7,
    destino: "CMU",
    ubicacion: "Costa Mujeres",
    status: "A",
    bandera: "cmu.svg",
    division: 904,
    superficie: "520000",
    habitaciones: 1146,
  },
  {
    idDestino: 10,
    destino: "AME",
    ubicacion: "America",
    status: "A",
    bandera: "all.svg",
    division: 0,
    superficie: null,
    habitaciones: 1,
  },
  {
    idDestino: 11,
    destino: "CAP",
    ubicacion: "Capcana",
    status: "A",
    bandera: "puj.svg",
    division: 917,
    superficie: "20000",
    habitaciones: 115,
  },
  {
    idDestino: 12,
    destino: "NYC",
    ubicacion: "45 Times Square",
    status: "A",
    bandera: "puj.svg",
    division: 917,
    superficie: "20000",
    habitaciones: 115,
  },
];
export const HOTELES = [
  {
    idHotel: 8,
    idDestino: 1,
    hotel: "GP WHITE SAND",
    marca: "GP",
  },
  {
    idHotel: 7,
    idDestino: 1,
    hotel: "GP KANTENAH",
    marca: "GP",
  },
  {
    idHotel: 6,
    idDestino: 1,
    hotel: "GP COLONIAL",
    marca: "GP",
  },
  {
    idHotel: 5,
    idDestino: 1,
    hotel: "TRS YUCATAN HOTEL",
    marca: "TRS",
  },
  {
    idHotel: 15,
    idDestino: 2,
    hotel: "FAMILY SELECTION AT GP VALLARTA",
    marca: "GP",
  },
  {
    idHotel: 14,
    idDestino: 2,
    hotel: "GP VALLARTA",
    marca: "GP",
  },
  {
    idHotel: 10,
    idDestino: 3,
    hotel: "DOMINICAN FIESTA",
    marca: "GP",
  },
  {
    idHotel: 28,
    idDestino: 4,
    hotel: "GP IMBASSAI",
    marca: "GP",
  },
  {
    idHotel: 4,
    idDestino: 5,
    hotel: "TRS TURQUESA",
    marca: "TRS",
  },
  {
    idHotel: 3,
    idDestino: 5,
    hotel: "GP PUNTA CANA",
    marca: "GP",
  },
  {
    idHotel: 2,
    idDestino: 5,
    hotel: "GP PALACE",
    marca: "GP",
  },
  {
    idHotel: 1,
    idDestino: 5,
    hotel: "GP BAVARO",
    marca: "GP",
  },
  {
    idHotel: 27,
    idDestino: 6,
    hotel: "GP LADY HAMILTON",
    marca: "GP",
  },
  {
    idHotel: 26,
    idDestino: 6,
    hotel: "GP JAMAICA",
    marca: "GP",
  },
  {
    idHotel: 13,
    idDestino: 7,
    hotel: "GP COSTA MUJERES",
    marca: "GP",
  },
  {
    idHotel: 12,
    idDestino: 7,
    hotel: "FAMILY SELECTION AT GP COSTA MUJERES",
    marca: "GP",
  },
  {
    idHotel: 11,
    idDestino: 7,
    hotel: "TRS CORAL HOTEL",
    marca: "TRS",
  },
  {
    idHotel: 25,
    idDestino: 11,
    hotel: "TRS CAP CANA",
    marca: "TRS",
  },
  {
    idHotel: 29,
    idDestino: 12,
    hotel: "NY",
    marca: "OY",
  },
];
